import { NextResponse } from "next/server";

// ═══════════════════════════════════════════════════════════════════
// SIDEKICK AUTO-BATCH PENDING
// GET /api/sidekick/auto-batch/pending?baseId=X
//
// Returns active batches (records in "Outreach" with Status=pending_approval),
// grouped by Batch ID, with all pre-generated drafts inline so the chatbot
// can render them without a second roundtrip.
// ═══════════════════════════════════════════════════════════════════

export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";
export const maxDuration = 30;

const AIRTABLE_KEY = process.env.AIRTABLE_API_KEY;
const SIDEKICK_API_KEY = process.env.SIDEKICK_API_KEY;
const AT_API = "https://api.airtable.com/v0";

function authOk(request) {
  if (!SIDEKICK_API_KEY) return false;
  const h = request.headers.get("authorization") || "";
  return h === `Bearer ${SIDEKICK_API_KEY}`;
}

export async function GET(request) {
  if (!authOk(request)) {
    return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
  }

  const url = new URL(request.url);
  const baseId = url.searchParams.get("baseId");
  if (!baseId) {
    return NextResponse.json({ ok: false, error: "baseId required" }, { status: 400 });
  }

  try {
    const qs = new URLSearchParams({
      filterByFormula: "{Status} = 'pending_approval'",
      pageSize: "100",
      "sort[0][field]": "Composite Score",
      "sort[0][direction]": "desc",
    });
    const r = await fetch(`${AT_API}/${baseId}/${encodeURIComponent("Outreach")}?${qs}`, {
      headers: { Authorization: `Bearer ${AIRTABLE_KEY}` },
      cache: "no-store",
    });

    if (!r.ok) {
      const t = await r.text();
      if (r.status === 403 && /INVALID_PERMISSIONS_OR_MODEL_NOT_FOUND/.test(t)) {
        return NextResponse.json({ ok: true, batches: [] });
      }
      // Sort field missing = degrade gracefully (no sort)
      if (r.status === 422) {
        const qs2 = new URLSearchParams({
          filterByFormula: "{Status} = 'pending_approval'",
          pageSize: "100",
        });
        const r2 = await fetch(`${AT_API}/${baseId}/${encodeURIComponent("Outreach")}?${qs2}`, {
          headers: { Authorization: `Bearer ${AIRTABLE_KEY}` },
          cache: "no-store",
        });
        if (!r2.ok) return NextResponse.json({ ok: false, error: "Airtable error" }, { status: 502 });
        const d2 = await r2.json();
        return NextResponse.json({ ok: true, batches: groupBatches(d2.records || []) });
      }
      return NextResponse.json({ ok: false, error: `Airtable ${r.status}` }, { status: 502 });
    }

    const d = await r.json();
    return NextResponse.json({ ok: true, batches: groupBatches(d.records || []) });
  } catch (e) {
    return NextResponse.json({ ok: false, error: e.message }, { status: 500 });
  }
}

function groupBatches(records) {
  // The connection note generated by deterministicFallback when AI fails
  // is a fixed-shape sentence. If a lead's note matches this pattern,
  // their personalization fell back — flag it so the chatbot can show
  // a warning and the operator can review the AI Debug field on the
  // Outreach record to find the root cause.
  //
  // Pattern: "Hi {firstName} — noticed your work at {company}. Would like to connect."
  const FALLBACK_CONNECTION_NOTE = /^Hi .+ — noticed your work at .+\. Would like to connect\.$/;
  const FALLBACK_DM1 = /^Thanks for connecting .+\. Curious how you're thinking about outbound at .+ this year\?$/;
  const FALLBACK_DM2 = /^Following up .+ — happy to share a quick teardown of how similar teams at .+'s scale are running outbound\. Would that be useful\?$/;
  const FALLBACK_DM3 = /^Last one .+ — no pressure\. If outbound is on the roadmap this year, I'd be glad to share what's working\. Either way, all the best\.$/;

  // Group by Batch ID
  const byBatch = new Map();
  for (const rec of records) {
    const f = rec.fields || {};
    const batchId = f["Batch ID"] || "no_batch";
    if (!byBatch.has(batchId)) byBatch.set(batchId, []);

    const connectionNote = f["Generated Connection Note"] || "";
    const dm1 = f["Generated DM 1"] || "";
    const dm2 = f["Generated DM 2"] || "";
    const dm3 = f["Generated DM 3"] || "";

    // Per-message fallback detection
    const fallbackFlags = {
      connection_note: FALLBACK_CONNECTION_NOTE.test(connectionNote),
      dm1: FALLBACK_DM1.test(dm1),
      dm2: FALLBACK_DM2.test(dm2),
      dm3: FALLBACK_DM3.test(dm3),
    };
    const allFallback = fallbackFlags.connection_note && fallbackFlags.dm1 && fallbackFlags.dm2 && fallbackFlags.dm3;
    const anyFallback = fallbackFlags.connection_note || fallbackFlags.dm1 || fallbackFlags.dm2 || fallbackFlags.dm3;

    byBatch.get(batchId).push({
      id: rec.id,
      lead_name: f["Lead Name"] || "Unknown",
      company: f.Company || "",
      title: f.Title || "",
      email: f.Email || "",
      linkedin_url: f["LinkedIn URL"] || "",
      post_url: f["Post URL"] || "",
      composite_score: f["Composite Score"] || 0,
      why_reasons: f["Why Reasons"] || "",
      connection_note: connectionNote,
      dm1,
      dm2,
      dm3,
      created_at: f["Created At"] || "",
      // AI personalization status — surface to chatbot so the operator
      // sees which leads were templated rather than personalized.
      ai_fallback_flags: fallbackFlags,
      ai_all_fallback: allFallback,
      ai_any_fallback: anyFallback,
      // Truncated AI Debug field so the chatbot can show why it fell back.
      // Full debug is on the Outreach record in Airtable.
      ai_debug: String(f["AI Debug"] || "").slice(0, 600),
    });
  }

  const batches = [];
  for (const [batchId, leads] of byBatch.entries()) {
    // Sort within batch by composite score desc
    leads.sort((a, b) => (b.composite_score || 0) - (a.composite_score || 0));
    batches.push({
      batch_id: batchId,
      count: leads.length,
      leads,
    });
  }

  // Sort batches by ID desc (most recent first)
  batches.sort((a, b) => (b.batch_id || "").localeCompare(a.batch_id || ""));
  return batches;
}
